Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 4e37fe3e-7f4d-4787-b296-7e6db399cc4b)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: c7e38f12-11a4-4719-adfb-566a1a35f045)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 059eecea-ddab-435e-8c8e-4359d4b7a91b)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: b233ac8b-205f-40da-8edd-488269b7a14d)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 84f897fa-8339-43db-8e82-4f1b2a64744d)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: ede5fb68-0213-4842-a6ad-1dcf81d3cd34)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/disk.py", line 98, in list_disks
    humanfriendly.format_size(int(disk.get('size'))),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 26b41407-cbce-4af7-baef-721408d8ce94)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: d69cb898-cf69-4c14-a6fd-d03818ff83d9)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 7c3091f3-72a4-4e70-b58c-c3322113a06e)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 8c0595fd-fa6c-4758-9ddc-9abbb90dfc10)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 98e87eb7-5019-45f9-afdb-935f864f0d1b)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/vm.py", line 391, in info
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 329555c2-70df-442a-9cd1-9e5f2a577a8b)

Traceback (most recent call last):
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/disk.py", line 79, in list_disks
    restore_session(ctx, vdc_required=True)
  File "/home/iresh/.local/lib/python3.8/site-packages/vcd_cli/utils.py", line 124, in restore_session
    client.rehydrate_from_token(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1045, in rehydrate_from_token
    self._response_code_to_exception(
  File "/home/iresh/.local/lib/python3.8/site-packages/pyvcloud/vcd/client.py", line 1190, in _response_code_to_exception
    raise UnauthorizedException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.UnauthorizedException: Status code: 401, <empty response body> (request id: 2344db47-c558-41ed-a970-e998d19c1820)

